spring:
  datasource:
    url:  jdbc:mysql://localhost/vollmed_api
    username: root
    password: 10210202

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    baseline-on-migrate: true

